export const drcLocations = {
  "Bas-Uele": ["Aketi", "Ango", "Bambesa", "Bondo", "Buta", "Poko"],
  Equateur: ["Basankusu", "Bikoro", "Bolomba", "Bomongo", "Ingende", "Lukolela", "Makanza", "Mbandaka"],
  "Haut-Katanga": ["Kambove", "Kasenga", "Kipushi", "Likasi", "Lubumbashi", "Mitwaba", "Pweto", "Sakania"],
  "Haut-Lomami": ["Bukama", "Kabongo", "Kamina", "Kaniama", "Malemba-Nkulu"],
  "Haut-Uele": ["Dungu", "Faradje", "Isiro", "Niangara", "Rungu", "Wamba", "Watsa"],
  Ituri: ["Aru", "Bunia", "Djugu", "Irumu", "Mahagi", "Mambasa"],
  Kasai: ["Dekese", "Ilebo", "Kamonia", "Luebo", "Mweka", "Tshikapa"],
  "Kasai-Central": ["Demba", "Dibaya", "Dimbelenge", "Kazumba", "Kananga", "Luiza"],
  "Kasai-Oriental": ["Kabeya-Kamwanga", "Katanda", "Lupatapata", "Miabi", "Mbuji-Mayi", "Tshilenge"],
  Kinshasa: [
    "Bandalungwa",
    "Barumbu",
    "Bumbu",
    "Gombe",
    "Kalamu",
    "Kasa-Vubu",
    "Kimbanseke",
    "Kinshasa",
    "Kintambo",
    "Kisenso",
    "Lemba",
    "Limete",
    "Lingwala",
    "Makala",
    "Maluku",
    "Masina",
    "Matete",
    "Mont-Ngafula",
    "Ndjili",
    "Ngaba",
    "Ngaliema",
    "Ngiri-Ngiri",
    "Nsele",
    "Selembao"
  ],
  "Kongo-Central": ["Boma", "Kasangulu", "Kimvula", "Lukula", "Luozi", "Madimba", "Matadi", "Mbanza-Ngungu", "Moanda", "Songololo", "Tshela"],
  Kwango: ["Feshi", "Kahemba", "Kasongo-Lunda", "Kenge", "Popokabaka"],
  Kwilu: ["Bagata", "Bandundu", "Bulungu", "Gungu", "Idiofa", "Masi-Manimba"],
  Lomami: ["Kabinda", "Kamiji", "Lubao", "Luilu", "Ngandajika"],
  Lualaba: ["Dilolo", "Kapanga", "Kolwezi", "Lubudi", "Mutshatsha", "Sandoa"],
  "Mai-Ndombe": ["Bolobo", "Inongo", "Kiri", "Kutu", "Mushie", "Oshwe", "Yumbi"],
  Maniema: ["Kabambare", "Kailo", "Kasongo", "Kibombo", "Kindu", "Lubutu", "Pangi", "Punia"],
  Mongala: ["Binga", "Bumba", "Bongandanga", "Lisala"],
  "Nord-Kivu": ["Beni", "Butembo", "Goma", "Lubero", "Masisi", "Nyiragongo", "Rutshuru", "Walikale"],
  "Nord-Ubangi": ["Bosobolo", "Businga", "Gbadolite", "Mobayi-Mbongo", "Yakoma"],
  Sankuru: ["Katako-Kombe", "Kole", "Lodja", "Lomela", "Lubefu", "Lusambo"],
  "Sud-Kivu": ["Bukavu", "Fizi", "Idjwi", "Kabare", "Kalehe", "Mwenga", "Shabunda", "Uvira", "Walungu"],
  "Sud-Ubangi": ["Budjala", "Gemena", "Kungu", "Libenge", "Zongo"],
  Tanganyika: ["Kabalo", "Kalemie", "Kongolo", "Manono", "Moba", "Nyunzu"],
  Tshopo: ["Bafwasende", "Banalia", "Basoko", "Isangi", "Kisangani", "Opala", "Ubundu", "Yahuma"],
  Tshuapa: ["Befale", "Boende", "Bokungu", "Djolu", "Ikela", "Monkoto"]
};

export const provinces = Object.keys(drcLocations);
