export const sampleReports = [
  {
    _id: "sample-001",
    title: "Bridge deck partially collapsed",
    description: "Flood water damaged the bridge deck and narrowed safe access for pedestrians and motorcycles.",
    crisisType: "flood",
    infrastructureType: "transport",
    category: "transport",
    damageLevel: "partial",
    imageUrl: "",
    province: "Kinshasa",
    commune: "Gombe",
    status: "verified",
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    location: { lat: -4.3224, lng: 15.307, address: "Gombe, Kinshasa" },
    likesCount: 8
  },
  {
    _id: "sample-002",
    title: "Health center wall cracked",
    description: "Visible structural cracks were reported after ground movement near the main consultation room.",
    crisisType: "earthquake",
    infrastructureType: "health",
    category: "health",
    damageLevel: "partial",
    imageUrl: "",
    province: "Nord-Kivu",
    commune: "Goma",
    status: "verified",
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    location: { lat: -1.6741, lng: 29.2285, address: "Goma, Nord-Kivu" },
    likesCount: 5
  },
  {
    _id: "sample-003",
    title: "Primary school roof destroyed",
    description: "Classrooms are exposed after fire damage. Temporary learning space is needed before reopening.",
    crisisType: "fire",
    infrastructureType: "education",
    category: "education",
    damageLevel: "complete",
    imageUrl: "",
    province: "Kongo-Central",
    commune: "Matadi",
    status: "pending",
    createdAt: new Date(Date.now() - 1000 * 60 * 130).toISOString(),
    location: { lat: -5.8166, lng: 13.45, address: "Matadi, Kongo-Central" },
    likesCount: 11
  },
  {
    _id: "sample-004",
    title: "Mobile tower power system damaged",
    description: "Communication service is unstable after the generator enclosure was damaged during unrest.",
    crisisType: "conflict",
    infrastructureType: "communication",
    category: "communication",
    damageLevel: "partial",
    imageUrl: "",
    province: "Ituri",
    commune: "Bunia",
    status: "verified",
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    location: { lat: 1.5667, lng: 30.25, address: "Bunia, Ituri" },
    likesCount: 6
  },
  {
    _id: "sample-005",
    title: "Water pump contaminated by debris",
    description: "Community members report debris and possible contamination around the main water point.",
    crisisType: "flood",
    infrastructureType: "utility",
    category: "utility",
    damageLevel: "minimal",
    imageUrl: "",
    province: "Sud-Kivu",
    commune: "Bukavu",
    status: "verified",
    createdAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    location: { lat: -2.5083, lng: 28.8608, address: "Bukavu, Sud-Kivu" },
    likesCount: 3
  },
  {
    _id: "sample-006",
    title: "Market stalls burned",
    description: "Several commercial stalls are unusable after a fire. Livelihoods are affected for vendors.",
    crisisType: "fire",
    infrastructureType: "commercial",
    category: "commercial",
    damageLevel: "complete",
    imageUrl: "",
    province: "Haut-Katanga",
    commune: "Lubumbashi",
    status: "verified",
    createdAt: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    location: { lat: -11.6647, lng: 27.4794, address: "Lubumbashi, Haut-Katanga" },
    likesCount: 14
  },
  {
    _id: "sample-007",
    title: "Government office windows shattered",
    description: "Blast pressure damaged windows and entry access. Interior records need protection from rain.",
    crisisType: "explosion",
    infrastructureType: "government",
    category: "government",
    damageLevel: "partial",
    imageUrl: "",
    province: "Kasai-Central",
    commune: "Kananga",
    status: "pending",
    createdAt: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    location: { lat: -5.8962, lng: 22.4166, address: "Kananga, Kasai-Central" },
    likesCount: 4
  },
  {
    _id: "sample-008",
    title: "Residential block unsafe",
    description: "Families report major wall separation after flooding weakened the structure.",
    crisisType: "flood",
    infrastructureType: "residential",
    category: "residential",
    damageLevel: "complete",
    imageUrl: "",
    province: "Mai-Ndombe",
    commune: "Inongo",
    status: "verified",
    createdAt: new Date(Date.now() - 1000 * 60 * 420).toISOString(),
    location: { lat: -1.95, lng: 18.2667, address: "Inongo, Mai-Ndombe" },
    likesCount: 10
  },
  {
    _id: "sample-009",
    title: "Public square access blocked",
    description: "Fallen debris blocks a public gathering space used for distribution and community notices.",
    crisisType: "other",
    infrastructureType: "public_space",
    category: "public_space",
    damageLevel: "partial",
    imageUrl: "",
    province: "Tshopo",
    commune: "Kisangani",
    status: "verified",
    createdAt: new Date(Date.now() - 1000 * 60 * 500).toISOString(),
    location: { lat: 0.5167, lng: 25.2, address: "Kisangani, Tshopo" },
    likesCount: 7
  },
  {
    _id: "sample-010",
    title: "Chemical spill near utility site",
    description: "Residents report odor and restricted access near a utility compound after a chemical incident.",
    crisisType: "chemical_incident",
    infrastructureType: "utility",
    category: "utility",
    damageLevel: "minimal",
    imageUrl: "",
    province: "Lualaba",
    commune: "Kolwezi",
    status: "rejected",
    createdAt: new Date(Date.now() - 1000 * 60 * 620).toISOString(),
    location: { lat: -10.7167, lng: 25.4667, address: "Kolwezi, Lualaba" },
    likesCount: 2
  }
];
